# -*- coding: utf-8 -*-
"""addition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UF-mYNp8S1cXWEvz4bn7mNEuByRMBubI
"""



"""addition of two programs"""

a=10
b=20
print("sum",a+b)

